// cesgen oracles — C++ parity side.
//
// Loads ../RealityEngine_Machines/oracles.json (generated by
// scripts/cesgen-oracles.mjs in RealityEngine_Machines) and runs every oracle
// through the C++ PerceptualSpaceRuntime.  The pass-set must match the
// recorded oracle pass-set on every push — that's the cross-runtime parity gate.
//
// For each oracle the test:
//   1. Loads the source machine JSON from the corpus.
//   2. Creates a fresh PerceptualSpaceRuntime and registers the machine
//      (auto-growing the perceptual space to fit its mapping).
//   3. Builds a dense input vector for each step in oracle.inputs.
//   4. Calls process_immediate once per step.
//   5. Asserts the expected (sequenceId, region, values) tuple is present
//      in the FINAL step's mergeBatch.
//
// The membership-not-uniqueness check mirrors src/__tests__/CesgenOracles.test.ts
// in the active Scala replacement: with GTE matching, a super-threshold input can
// fire several sibling vectors in the same step, so the oracle assertion is "the expected
// output value appeared," not "it was the only output."
//
// Argv:
//   cesgen_oracles_parity [oracles.json] [machines_dir]
// Default paths assume the standard side-by-side layout (run from the C++ repo).

#include "reality/reality.hpp"
#include "reality/json.hpp"

#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

using namespace reality;

namespace {

// Every position the oracle expects is present in the folded operation at at
// least the expected magnitude. Length is compared too: a fold that dropped
// positions is a defect, not a subsumption.
bool values_subsumed(const std::vector<double>& expected, const std::vector<double>& folded) {
  if (folded.size() < expected.size()) return false;
  for (size_t i = 0; i < expected.size(); ++i) {
    if (folded[i] + 1e-9 < expected[i]) return false;
  }
  return true;
}

std::string read_file(const std::filesystem::path& p) {
  std::ifstream in(p);
  if (!in) throw std::runtime_error("cannot read " + p.string());
  std::stringstream ss; ss << in.rdbuf();
  return ss.str();
}

struct Region { int offset = 0; int length = 0; };

struct Oracle {
  std::string id;
  std::string machineFile;
  std::string sequenceId;
  std::string kind;
  Region inputRegion;
  std::vector<std::vector<double>> inputs;
  Region expectedRegion;
  std::vector<double> expectedValues;
  std::string outputMergeTransformation = "or";
};

// A machine presents ONE Reality Event per instant, not one per sequence: the
// engine folds its collection of potential outputs at the completion boundary
// of the atomic matching action (FOLD_PLACEMENT.md). mergeBatch therefore
// carries one operation per machine, and an individual outputVector is no
// longer separately observable in it.
//
// The oracles are generated per outputVector, which is the right unit to
// generate — it is what the corpus declares. It stopped being the right unit to
// *assert* when the fold landed. 68 of 4966 oracles failed for exactly this:
// each expected value was present in the folded operation, alongside the other
// outputs that fired at the same instant.
//
//     aict-mem-critical::0  expected  0 0 1 0 0 0
//     aict-mem-critical::1  expected  0 0 0 0 0 1
//     folded operation                0 0 1 0 0 1
//
// Under a monotone fold a contribution can only add — so the assertion that
// survives is that the expectation is subsumed by the fold, not that it appears
// intact. That still catches a missing contribution, a wrong region and a wrong
// machine; what it gives up is detecting extra positions, which under a
// monotone fold are the other sequences legitimately contributing.
//
// Only for monotone transformations. `and`, `nor`, `nand`, `xor`, `meet`,
// `strong-conjunction` and `discrete-median` can all lower a position, so
// subsumption would be unsound there and the exact match is kept. No corpus
// machine selects one today — 4956 oracles are `or` and 10 are `join` — which
// is precisely why it is written down rather than left implied.
bool fold_is_monotone(const std::string& transformation) {
  return transformation == "or" || transformation == "max" ||
         transformation == "join" || transformation == "strong-disjunction";
}

Oracle parse_oracle(const Json& o) {
  Oracle out;
  out.id          = o.at("id").as_string();
  out.machineFile = o.at("machineFile").as_string();
  out.sequenceId  = o.at("sequenceId").as_string();
  out.kind        = o.at("kind").as_string();
  out.inputRegion = {
    static_cast<int>(o.at("inputRegion").at("offset").as_number()),
    static_cast<int>(o.at("inputRegion").at("length").as_number()),
  };
  for (const auto& row : o.at("inputs").array()) {
    out.inputs.push_back(json::to_numbers(row));
  }
  const auto& exp = o.at("expected");
  out.expectedRegion = {
    static_cast<int>(exp.at("region").at("offset").as_number()),
    static_cast<int>(exp.at("region").at("length").as_number()),
  };
  out.expectedValues = json::to_numbers(exp.at("values"));
  // Absent means "or" — both because that is the corpus default and because an
  // oracle file generated before this field existed must keep working.
  if (!o.at("outputMergeTransformation").is_null())
    out.outputMergeTransformation = o.at("outputMergeTransformation").as_string("or");
  return out;
}

Vector dense_input(const Region& r, const std::vector<double>& values) {
  Vector v(static_cast<size_t>(r.offset + r.length), 0.0);
  int n = std::min<int>(r.length, static_cast<int>(values.size()));
  for (int i = 0; i < n; ++i) v[static_cast<size_t>(r.offset + i)] = values[static_cast<size_t>(i)];
  return v;
}

bool values_equal(const Vector& a, const std::vector<double>& b) {
  if (a.size() != b.size()) return false;
  for (size_t i = 0; i < a.size(); ++i) if (a[i] != b[i]) return false;
  return true;
}

std::string format_vector(const Vector& v) {
  std::ostringstream ss;
  ss << "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i) ss << ",";
    ss << v[i];
  }
  ss << "]";
  return ss.str();
}

} // namespace

int main(int argc, char** argv) {
  std::filesystem::path oracleFile  = argc > 1 ? argv[1] : "../RealityEngine_Machines/oracles.json";
  std::filesystem::path machinesDir = argc > 2 ? argv[2] : "../RealityEngine_Machines/machines";

  if (!std::filesystem::exists(oracleFile)) {
    std::cerr << "Skipping cesgen_oracles_parity — oracles file not found: " << oracleFile << "\n";
    return 0;
  }
  if (!std::filesystem::exists(machinesDir)) {
    std::cerr << "Skipping cesgen_oracles_parity — machines dir not found: " << machinesDir << "\n";
    return 0;
  }

  // Parse the oracles file.  This is JSON-heavy work but happens once.
  Json doc = json::parse(read_file(oracleFile));
  std::vector<Oracle> oracles;
  oracles.reserve(static_cast<size_t>(doc.at("oracleCount").as_number()));
  for (const auto& o : doc.at("oracles").array()) oracles.push_back(parse_oracle(o));

  // Cache machine JSON text by file so we read each source once.
  std::map<std::string, std::string> rawByFile;
  auto raw_for = [&](const std::string& f) -> const std::string& {
    auto it = rawByFile.find(f);
    if (it != rawByFile.end()) return it->second;
    return rawByFile[f] = read_file(find_machine_file(machinesDir, f));
  };

  auto t0 = std::chrono::steady_clock::now();
  int passed = 0;
  int failed = 0;
  // Was a hard 5 with no override, which is not enough to characterise a
  // failure set: diagnosing the 68 fold failures meant editing this constant,
  // rebuilding and reverting. ORACLE_FAILURE_LIMIT=0 reports all of them.
  size_t failureLimit = 5;
  if (const char* env = std::getenv("ORACLE_FAILURE_LIMIT")) {
    char* end = nullptr;
    const long parsed = std::strtol(env, &end, 10);
    if (end != env && parsed >= 0) failureLimit = parsed == 0 ? SIZE_MAX : static_cast<size_t>(parsed);
  }
  std::vector<std::string> firstFailures;

  for (size_t idx = 0; idx < oracles.size(); ++idx) {
    const auto& o = oracles[idx];
    try {
      Machine m = load_machine_from_json_string(raw_for(o.machineFile),
                                                "oracle::" + std::to_string(idx));
      PerceptualSpaceRuntime sim(0);
      sim.add_machine(m);

      SimulationStep last;
      for (const auto& stepInput : o.inputs) {
        last = sim.process_immediate(dense_input(o.inputRegion, stepInput));
      }

      const bool monotone = fold_is_monotone(o.outputMergeTransformation);
      bool hit = false;
      for (const auto& op : last.mergeBatch) {
        if (!contributed(op, o.sequenceId)
            || op.region.offset != o.expectedRegion.offset
            || op.region.length != o.expectedRegion.length) continue;
        if (monotone ? values_subsumed(o.expectedValues, op.values)
                     : values_equal(op.values, o.expectedValues)) {
          hit = true;
          break;
        }
      }
      if (hit) {
        ++passed;
      } else {
        ++failed;
        if (firstFailures.size() < failureLimit) {
          std::ostringstream ss;
          ss << o.id << " — expected ";
          for (double v : o.expectedValues) ss << v << " ";
          ss << "not present in mergeBatch (";
          for (const auto& op : last.mergeBatch) ss << format_vector(op.values) << " ";
          ss << ")";
          firstFailures.push_back(ss.str());
        }
      }
    } catch (const std::exception& e) {
      ++failed;
      if (firstFailures.size() < failureLimit) firstFailures.push_back(o.id + " — exception: " + e.what());
    }
  }

  auto t1 = std::chrono::steady_clock::now();
  double seconds = std::chrono::duration<double>(t1 - t0).count();

  std::cout << "cesgen oracles parity summary\n"
            << "  oracle file:     " << oracleFile << "\n"
            << "  oracles total:   " << oracles.size() << "\n"
            << "  passed:          " << passed << "\n"
            << "  failed:          " << failed << "\n"
            << "  elapsed (s):     " << seconds << "\n";

  if (failed > 0) {
    std::cerr << "FAILURES (showing first " << firstFailures.size() << "):\n";
    for (const auto& f : firstFailures) std::cerr << "  " << f << "\n";
    std::cerr << "cesgen_oracles_parity FAILED\n";
    return 1;
  }
  std::cout << "cesgen_oracles_parity passed\n";
  return 0;
}
