// CES contracts — C++ side of the cross-runtime parity gate.
//
// Loads ../RealityEngine_Machines/contracts.json (generated by
// scripts/cesgen-contracts.mjs in RealityEngine_Machines) and replays every
// contract's input chain through the C++ PerceptualSpaceSimulator,
// step-by-step.  At each step the recorded mergeBatch + eventBus must
// match what C++ produces exactly.
//
// Difference from cesgen_oracles_parity (step 2):
//   - Oracles assert the FINAL step's mergeBatch contains an expected entry.
//   - Contracts assert EVERY step's mergeBatch + eventBus matches exactly.
//
// This catches the failure mode from the original brief: a silent
// dimension-bound skip on one runtime would zero out outputs at every
// step where a skipped machine should have fired — the contract diff
// would be eight domains' worth of "expected entries, got nothing."

#include "reality/reality.hpp"
#include "reality/json.hpp"

#include <chrono>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace reality;

namespace {

std::string read_file(const std::filesystem::path& p) {
  std::ifstream in(p);
  if (!in) throw std::runtime_error("cannot read " + p.string());
  std::stringstream ss; ss << in.rdbuf();
  return ss.str();
}

Vector dense_input(int offset, int length, const std::vector<double>& values) {
  Vector v(static_cast<size_t>(offset + length), 0.0);
  int n = std::min<int>(length, static_cast<int>(values.size()));
  for (int i = 0; i < n; ++i) v[static_cast<size_t>(offset + i)] = values[static_cast<size_t>(i)];
  return v;
}

/**
 * Render one engine step's mergeBatch + eventBus as a compact JSON string
 * matching the contract file's shape — so a string-equality compare is
 * the parity check (drift anywhere shows up in the diff).
 */
std::string project_step(const SimulationStep& s) {
  Json::Array mb;
  for (const auto& op : s.mergeBatch) {
    Json::Array prov;
    for (const auto& vid : op.provenance) prov.emplace_back(vid);
    Json::Object o;
    o["region"]      = Json::Object{{"offset", static_cast<double>(op.region.offset)}, {"length", static_cast<double>(op.region.length)}};
    o["sequenceId"]  = op.sequenceId;
    o["outputIndex"] = static_cast<double>(op.outputIndex);
    Json::Array vals; for (double v : op.values) vals.emplace_back(v);
    o["values"]      = vals;
    o["provenance"]  = prov;
    mb.push_back(o);
  }
  Json::Array eb;
  for (const auto& w : s.eventBus) {
    Json::Array prov;
    for (const auto& vid : w.provenance) prov.emplace_back(vid);
    Json::Object o;
    o["producerSequenceId"] = w.producerSequenceId;
    o["bitOffset"]          = static_cast<double>(w.bitOffset);
    o["value"]              = w.value;
    o["provenance"]         = prov;
    eb.push_back(o);
  }
  return json::stringify(Json::Object{{"mergeBatch", mb}, {"eventBus", eb}});
}

/** Same projection of a recorded contract step. */
std::string project_recorded_step(const Json& recorded) {
  Json::Object o{
    {"mergeBatch", recorded.at("mergeBatch")},
    {"eventBus",   recorded.at("eventBus")},
  };
  return json::stringify(o);
}

} // namespace

int main(int argc, char** argv) {
  std::filesystem::path contractsFile = argc > 1 ? argv[1] : "../RealityEngine_Machines/contracts.json";
  std::filesystem::path machinesDir   = argc > 2 ? argv[2] : "../RealityEngine_Machines/machines";

  if (!std::filesystem::exists(contractsFile)) {
    std::cerr << "Skipping cesgen_contracts_parity — contracts file not found: " << contractsFile << "\n";
    return 0;
  }
  if (!std::filesystem::exists(machinesDir)) {
    std::cerr << "Skipping cesgen_contracts_parity — machines dir not found: " << machinesDir << "\n";
    return 0;
  }

  Json doc = json::parse(read_file(contractsFile));
  const auto& contracts = doc.at("contracts").array();

  // Cache machine JSON text by file — saves thousands of disk reads.
  std::map<std::string, std::string> rawByFile;
  auto raw_for = [&](const std::string& f) -> const std::string& {
    auto it = rawByFile.find(f);
    if (it != rawByFile.end()) return it->second;
    return rawByFile[f] = read_file(find_machine_file(machinesDir, f));
  };

  auto t0 = std::chrono::steady_clock::now();
  int passed = 0, failed = 0;
  std::vector<std::string> firstFailures;
  size_t totalSteps = 0;

  for (size_t idx = 0; idx < contracts.size(); ++idx) {
    const Json& c = contracts[idx];
    std::string id = c.at("id").as_string();
    std::string machineFile = c.at("machineFile").as_string();
    int off = static_cast<int>(c.at("inputRegion").at("offset").as_number());
    int len = static_cast<int>(c.at("inputRegion").at("length").as_number());

    try {
      Machine m = load_machine_from_json_string(raw_for(machineFile),
                                                "contract::cpp::" + std::to_string(idx));
      PerceptualSpaceSimulator sim(0);
      sim.add_machine(m);

      const auto& inputs = c.at("inputs").array();
      const auto& stream = c.at("outputStream").array();
      if (inputs.size() != stream.size()) {
        ++failed;
        if (firstFailures.size() < 10) firstFailures.push_back(id + " — inputs/outputStream length mismatch");
        continue;
      }

      bool ok = true;
      for (size_t i = 0; i < inputs.size(); ++i) {
        std::vector<double> vals = json::to_numbers(inputs[i]);
        SimulationStep step = sim.process_immediate(dense_input(off, len, vals));
        ++totalSteps;
        std::string actual   = project_step(step);
        std::string expected = project_recorded_step(stream[i]);
        if (actual != expected) {
          ok = false;
          if (firstFailures.size() < 10) {
            firstFailures.push_back(id + " step " + std::to_string(i) +
              " mismatch\n      expected: " + expected.substr(0, 220) +
              "\n      actual:   " + actual.substr(0, 220));
          }
          break;
        }
      }
      if (ok) ++passed;
      else    ++failed;
    } catch (const std::exception& e) {
      ++failed;
      if (firstFailures.size() < 10) firstFailures.push_back(id + " — exception: " + e.what());
    }
  }

  auto t1 = std::chrono::steady_clock::now();
  double seconds = std::chrono::duration<double>(t1 - t0).count();

  std::cout << "cesgen contracts parity summary\n"
            << "  contracts file:   " << contractsFile << "\n"
            << "  contracts total:  " << contracts.size() << "\n"
            << "  passed:           " << passed << "\n"
            << "  failed:           " << failed << "\n"
            << "  steps replayed:   " << totalSteps << "\n"
            << "  elapsed (s):      " << seconds << "\n";
  if (failed > 0) {
    std::cerr << "FAILURES (showing first " << firstFailures.size() << "):\n";
    for (const auto& f : firstFailures) std::cerr << "  " << f << "\n";
    std::cerr << "cesgen_contracts_parity FAILED\n";
    return 1;
  }
  std::cout << "cesgen_contracts_parity passed\n";
  return 0;
}
